// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibsxglkvcfenutoqkfvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlic3hnbGt2Y2ZlbnV0b3FrZnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTkyNDUsImV4cCI6MjA2OTIzNTI0NX0.lk9kCQ1aiiiMgmuG5HZjSXf-I9M4KrHHaIu9b23iYBk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});